### ISSUE TITLE
Screen Recording Launch Issue for Older OS

### ISSUE THREAD

**Issue by CharliePieczonka** [MCMi460/OpenEmuRPC#10]
I'm having issues at launch related to screen recording while running OS High Sierra (10.13), but it appears the screen recording privacy permissions was only introduced in [Catalina (10.15)](https://support.apple.com/en-ca/guide/mac-help/mh32356/10.15/mac/10.15). Wondering if theres a possible work around for older OS?

**Comment by MCMi460** [comment]
I'm going to need to find a way to replicate this; I'm installing a Mojave VM to test a fix.

**Comment by MCMi460** [comment]
OpenEmu itself currently only supports Mojave (10.14), but for those using Mojave (or older builds of OpenEmu), the latest release that's coming out in a few moments _should_ fix those problems for you.
(see 39b19058dde5744b36364715009ea7d9974f9acb)
Thank you for telling me about this!

**Comment by MCMi460** [comment]
I'm going to close this issue for now; please reopen it if the x86_64 build in https://github.com/MCMi460/OpenEmuRPC/releases/tag/v1.2 does not work for you. Thank you!

**Comment by CharliePieczonka** [comment]
Hey, just got back to this. Thank you for looking into it!

I don't want to reopen this issue just yet but I'm still having issues. If I download the x86_64.zip, unzip it, and open the OpenEmuRPC.app I get the error as seen in the picture. 
<img width="421" alt="Screen Shot 2023-06-06 at 6 03 27 PM" src="https://github.com/MCMi460/OpenEmuRPC/assets/49101768/ac4d0d3f-673f-440f-b6f6-85ba91275a65">
I tried looking through the console logs and it didn't seem too helpful, but I could get those as well if you want to look.

However, if I run the main.py through IDLE or terminal it runs as intended and I don't have any problems. Any help is appreciated!

**Comment by MCMi460** [comment]
Hm, that is very odd. I'll try replicating that when I get home and see what's happening. Thank you for notifying me about this, and I'm glad that it's working as main.py now!

**Comment by MCMi460** [comment]
![Screenshot 2023-06-06 at 10 20 16 PM](https://github.com/MCMi460/OpenEmuRPC/assets/32529306/e31e164b-9ac8-47f1-8c73-3cb6cfd9dcc2)
Oddly enough, running the executable itself gives no error.
I'm hereby reopening this issue haha.

**Comment by MCMi460** [comment]
I can also confirm that, seemingly, it works fine when running via script.
(Though I cannot run OpenEmu to test this as my VM has limitations, despite being version 10.14.4)

**Comment by MCMi460** [comment]
Building on 10.14.4 creates a working build. I'll check to see if it is forwards compatible.
I really want to know what went wrong here, though.

**Comment by MCMi460** [comment]
I'm sorry, it appears that I _do_ get an error message, I was simply just running the wrong build.
Here it is:
![Screenshot 2023-06-06 at 10 42 58 PM](https://github.com/MCMi460/OpenEmuRPC/assets/32529306/4b5dc0bf-ad3a-4020-8d03-16160cc3da96)
Seems to be because the latest `libintl.8.dylib` does not support the load command `0x80000034`, but the older ones do? Not sure about this.
I've tried the build from 10.14.4, but it fails to work with Discord on my M1 Mac, so perhaps a specific split between x86_64 and x86_64(pre 10.15) will be necessary?

**Comment by MCMi460** [comment]
I'm not going to pretend that I understand py2app's magic, but it does seem like Python3.10 builds with libintl.8 and Python3.11 builds _without_ it. Either that or Github Actions specifically builds with it, for whatever reason, but I doubt it. I'm going to try updating Github Actions to Python 3.11.3 and see if that changes anything.
Expect a beta build in a moment.

**Comment by MCMi460** [comment]
Okay, that update seems to have fixed things -- at least for me. I'm going to release v1.2.1 now. When you are able, could you verify that the build at [v1.2.1/x86_64.zip](https://github.com/MCMi460/OpenEmuRPC/releases/download/v1.2.1/x86_64.zip) works? Thanks!

**Comment by CharliePieczonka** [comment]
>  Seems to be because the latest `libintl.8.dylib` does not support the load command `0x80000034`, but the older ones do? Not sure about this. I've tried the build from 10.14.4, but it fails to work with Discord on my M1 Mac, so perhaps a specific split between x86_64 and x86_64(pre 10.15) will be necessary?

Trying to mess around with py2app myself I was getting a similar error surrounding libintl.8.dylib, but I certainly didn't understand much.

As of your newest build it is now working! Thanks!

**Comment by MCMi460** [comment]
> As of your newest build it is now working! Thanks!

Sweet, I'm glad to hear it!
Thank you for bringing this to my attention!
