### ISSUE TITLE
Arm64 Fatal Error

### ISSUE THREAD

**Issue by ItsLame** [MCMi460/OpenEmuRPC#6]
Happens when trying to launch the arm64 version. I'm on MBP M1 Pro 14".

<img width="372" alt="image" src="https://user-images.githubusercontent.com/37344470/233052464-7feaf53b-2154-4390-8229-21a42082424d.png">

<img width="525" alt="image" src="https://user-images.githubusercontent.com/37344470/233053062-da54c8dd-da52-4844-80ed-c444ec26eb92.png">

**Comment by Delation** [comment]
@MCMi460 Research this one, please. It isn't one I've experienced yet.

**Comment by MCMi460** [comment]
Does this error happen when running `main.py`?

**Comment by ItsLame** [comment]
Running from `x86_64.zip` works.
Running the app from `main.py` through both rosetta and arm terminal works fine as well.

**Comment by ItsLame** [comment]
Just tried building from `build.py`, and there was no problem running that. But the file size is a tad bit bigger (?)

<img width="261" alt="image" src="https://user-images.githubusercontent.com/37344470/233837970-d1bd5348-6d95-4cce-a731-586307c6e9c1.png">

Can you guys try running this?
[OpenEmuRPC.zip](https://github.com/MCMi460/OpenEmuRPC/files/11303622/OpenEmuRPC.zip)

**Comment by MCMi460** [comment]
I'm thinking that I messed up something when building on my machine, but I'm planning on doing another release later today, and I'll make sure that it works then.
Thanks for bringing this to my attention!

**Comment by MCMi460** [comment]
Alright, it appears the problem was building a virtual environment(?). Seemingly, just building from `build.py` worked just fine, so I'll doing that from now on.

**Comment by MCMi460** [comment]
Please tell me if the build on this release works for you on your M1 Mac: https://github.com/MCMi460/OpenEmuRPC/releases/tag/v1.2

**Comment by ItsLame** [comment]
> Please tell me if the build on this release works for you on your M1 Mac: https://github.com/MCMi460/OpenEmuRPC/releases/tag/v1.2

Heyy just tested. I still got fatal error for arm64.

**Comment by MCMi460** [comment]
I'm building on a Mac M1, so I don't know why. To be honest, since the x86_64 version works on arm64 as well, I'm inclined to just remove the M1 builds and have everyone use the Intel builds instead.

**Comment by MCMi460** [comment]
For now, I'm just going to be using `x86_64` builds with Intel chips that can run on Apple Silicon devices under Rosetta 2 -- at least until Github supports Apple Silicon Mac runners in Workflows.
Thank you for telling me about this, though!
