### ISSUE TITLE
Wrong Art Cover

### ISSUE THREAD

**Issue by ItsLame** [MCMi460/OpenEmuRPC#7]
Both `x86_64` and `arm`. Supposed to show this: 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/37344470/233838310-6afadf3b-dbeb-4179-bdcd-4b7c0323039a.png">

Got this instead:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/37344470/233837774-dbb853b9-5e2c-4d6d-a06d-422f912a0668.png">

**Comment by ItsLame** [comment]
Fix PR: #8

**Comment by MCMi460** [comment]
With pull request #8 merged, this issue is no longer a problem. Thank you @ItsLame!
