### ISSUE TITLE
Cover Art Issues

### ISSUE THREAD

**Issue by JohnjiRomanji** [MCMi460/OpenEmuRPC#9]
The cover art for some games is wrong or just doesn't show up: 

Case 1: Pokemon Emerald for GBA shows up as GTA: Liberty City Stories for PSP

<img width="202" alt="Screenshot 2023-05-13 at 11 05 01 AM" src="https://github.com/MCMi460/OpenEmuRPC/assets/69640272/cdc2ccfc-cd8d-4030-8918-e09892ab29e8">
<img width="287" alt="Screenshot 2023-05-13 at 11 05 05 AM" src="https://github.com/MCMi460/OpenEmuRPC/assets/69640272/c753f78e-5ea3-4418-a3cd-45fc6db159ee">

Case 2: Gran Turismo for PSP has no art
<img width="130" alt="Screenshot 2023-05-13 at 11 05 32 AM" src="https://github.com/MCMi460/OpenEmuRPC/assets/69640272/6b1ad31f-ea58-44aa-89a7-26d2ad01247a">
<img width="255" alt="Screenshot 2023-05-13 at 11 05 27 AM" src="https://github.com/MCMi460/OpenEmuRPC/assets/69640272/3bb02f02-0451-464b-96a8-22a775596ac0">

**Comment by MCMi460** [comment]
With pull request #8 merged, this issue is no longer a problem. Thank you @ItsLame!
